site_name: vfTest
site_description: Documentation for vfTest
nav:
  - Process Inventory: index.md
  - Visual Flow Diagrams: diagrams.md
  - Global Variables: variables.md
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
extra_css:
  - stylesheets/extra.css
