apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: wssecurity
  title: "WSSecurity"
  description: "Shared interface: WSSecurity.wsdl (provided by balancemanagement-surepay-26-1-4)"
  tags:
    - tibco
    - bw5
spec:
  type: openapi
  lifecycle: production
  owner: group:default/tibco-imported
  system: system:default/tibco-bw5-estate
  definition: |
    <?xml version="1.0" encoding="UTF-8"?>
    <!-- ICC: 23/05/2012 - LIB_FRAMEWORK_4_0_0 -->
    <!-- ICC: First version -->
    <!-- TILV2: Header: /cvs/TIL_V2/SharedResources/SchemaDefinitions/Vodafone/GITA1/GITA2/GITA3/MyOperation.wsdl,v 1.7 2008/08/01 11:45:28 ayelr Exp  -->
    <!-- PXX: $Header: /cvs/TIL_CORE/TIL_FW_01/SharedResources/SchemaDefinitions/Common/wsdl/WSSecurity.wsdl,v 1.2 2012/05/29 15:08:09 ayelr Exp $ -->
    <definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:tns="http://xmlns.tibco.com/common/wsdl/WSSecurity" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.tibco.com/common/wsdl/WSSecurity" name="WSSecurity">
        <import location="../../Others/docs.oasis-open.org/wss/2004/01/wss-wssecurity-secext.xsd" namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"/>
        <message name="WSSecurityHeader">
            <part element="ns:Security" name="wssecurity"/>
        </message>
    </definitions>
