site_name: TIL_OSM_Adapter_1-22_2_1
site_description: Documentation for TIL_OSM_Adapter_1-22_2_1
nav:
  - Process Inventory: index.md
  - Visual Flow Diagrams: diagrams.md
  - Global Variables: variables.md
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
extra_css:
  - stylesheets/extra.css
