apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: jms-dest-processes-itintegration-applicationintegration-routing
  title: "%%Processes/ITIntegration/ApplicationIntegration/Routing/OSMtoTILRouter/Operation4/MIG_OSMRequestQueue%%"
  description: "%%Processes/ITIntegration/ApplicationIntegration/Routing/OSMtoTILRouter/Operation4/MIG_OSMRequestQueue%%"
  tags:
    - tibco
    - bw5
    - messaging
    - jms
    - destination
spec:
  type: jms-destination
  lifecycle: production
  owner: group:default/tibco-imported
  system: system:default/tibco-bw5-estate
