site_name: TIL_HSS_DiameterAdapter-25_11_1
site_description: Documentation for TIL_HSS_DiameterAdapter-25_11_1
nav:
  - Process Inventory: index.md
  - Visual Flow Diagrams: diagrams.md
  - Global Variables: variables.md
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
